name: Publish Windows and Linux Apps

on:
  push:
    branches: ['main']
    tags: ['v*.*.*']
  
jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci

      - name: Decode Code Signing Certificate
        run: |
          echo ${{ secrets.development.CA }} | base64 -d > devcert.pfx
        env:
          CERTIFICATE_PFX: ${{ secrets.CERTIFICATE_PFX }}

      - name: Publish Windows Installer
        run: npx electron-forge publish
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci

      - name: Decode Code Signing Certificate
        run: |
          echo ${{ secrets.development.CA }} | base64 -d > devcert.pfx
        env:
          CERTIFICATE_PFX: ${{ secrets.CERTIFICATE_PFX }}
      
      - name: Publish Linux Installer
        run: npx electron-forge publish
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}